name: Packages

on:
  pull_request:

  push:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Read node version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Type check
        run: yarn typedef
