name: WinGet

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to use for the release"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set tag name
        env:
          TAG_NAME: ${{ inputs.tag_name || github.event.release.tag_name }}
        run: echo "WINGET_TAG_NAME=$(echo ${TAG_NAME#v})" >> $GITHUB_ENV

      - name: Submit package
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Triplex.Triplex
          installers-regex: '^Triplex-Setup-[\d\.]+\.exe$'
          version: ${{ env.WINGET_TAG_NAME }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          token: ${{ secrets.WINGET_ACC_TOKEN }}
          fork-user: triplex-bot
