name: Cloud

on:
  pull_request:
    paths:
      - packages/**
      - apps/cloud/**

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    timeout-minutes: 5

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm i

      - name: Build cloud
        run: pnpm --filter @triplex/cloud build

      - name: Typecheck
        run: pnpm --filter @triplex/cloud typedef

      - name: Ensure clean git
        run: node ./scripts/ensure-clean-git.js
