name: Electron

on:
  pull_request:
    paths:
      - apps/electron/**
      - packages/**

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Read node version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: "pnpm"

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm i

      - name: Build targets
        run: pnpm electron:build-targets
