name: Packages

on:
  pull_request:
    paths:
      - apps/**
      - packages/**

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Read node version
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
          cache: "pnpm"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm i

      - name: Test packages
        run: pnpm test

      - name: Lint packages
        run: pnpm lint
